# Generated by Django 5.2.7 on 2025-11-04 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidores', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribuidor',
            options={'verbose_name': 'Distribuidor', 'verbose_name_plural': 'Distribuidores'},
        ),
        migrations.RenameField(
            model_name='distribuidor',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AddField(
            model_name='distribuidor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distribuidor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='empresa',
            field=models.CharField(blank=True, default='Sin empresa', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='telefono',
            field=models.CharField(blank=True, default='Sin telefono', max_length=30),
            preserve_default=False,
        ),
    ]
