# Generated by Django 5.2.7 on 2025-11-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_descuento_porcentaje_venta_descuento_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='es_gabi',
            field=models.BooleanField(default=False),
        ),
    ]
