# Generated by Django 5.2.7 on 2025-11-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_iniciales'),
        ('ventas', '0003_venta_es_gabi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='proveedor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='proveedores.proveedor'),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
