# Generated by Django 5.2.7 on 2025-10-28 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Use solo dígitos y opcional + al inicio (7–15 dígitos).', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Use solo dígitos y opcional + al inicio (7–15 dígitos).', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
