# Generated by Django 5.2.7 on 2025-11-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_telefono_usuario_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('Distribuidor', 'Distribuidor'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
