# Generated by Django 5.2.7 on 2025-11-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(help_text='Nombre de usuario con espacios permitido.', max_length=150, unique=True),
        ),
    ]
