# Generated by Django 5.2.7 on 2025-12-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_options_producto_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='activo',
        ),
        migrations.AddField(
            model_name='producto',
            name='es_cuenta_completa',
            field=models.BooleanField(default=False, help_text='Indica si este producto es una cuenta completa (ej: Netflix Completa).'),
        ),
        migrations.AddField(
            model_name='producto',
            name='perfiles_cuenta',
            field=models.PositiveIntegerField(default=1, help_text='Número de perfiles que tiene este producto si es cuenta completa (ej: 5 para Netflix).'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
