# Generated by Django 5.2.7 on 2025-12-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_options_remove_producto_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el producto está disponible para usar en ventas.'),
        ),
    ]
