# Generated by Django 5.2.7 on 2025-11-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='iniciales',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
